name: Generate Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  generateDocumentation:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nim with Homebrew
        run: brew install nim
      - name: Install nimplex and dependencies
        run: nimble install
      - name: Build documentation
        run: |
          cd docs
          nim c -r -d:ssl -d:changelogType=nim -d:user=amkrajewski -d:repo=nimplex getChangelog                  
          cd ..
          sed -i '' 's/assets/nimplex\/assets/g' docs/docs.nim
          sed -i '' 's/assets/nimplex\/assets/g' nimplex.nim
          nim doc --outdir:docs --index:on --git.url:https://github.com/amkrajewski/nimplex --git.commit:main --docInternal --project nimplex.nim
          sed -i '' '26i\
          <img src="../nimplex/assets/logo.png" alt="Logo" style="width:200px;height:170px;margin:20px 0px 20px 20px;"/>' docs/nimplex.html
          sed -i '' '12d' docs/nimplex.html
          sed -i '' '12d' docs/nimplex.html
          sed -i '' '12i\
          <link rel="icon" href="favicon.ico" type="image/x-icon"><link rel="shortcut icon" href="favicon.ico" type="image/x-icon">' docs/nimplex.html
          cp docs/nimplex.html docs/index.html
      - name: Copy assets to docs
        run: cp -r assets docs/assets
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/

  deploy:
    needs: generateDocumentation
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: documentation
          path: docs/
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4