name: Linux (Ubuntu) Tests

on:
  push:
    paths:
      - 'tests/**'
      - 'nimplex.nim'
      - 'nimplex.nimble'
      - '.github/workflows/testingOnPush_Linux.yaml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim:
          - '2.0.x'
          - 'stable'
          - 'devel'
    name: Nim ${{ matrix.nim }} Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install BLAS and PCRE
        run: sudo apt-get install -y libopenblas-dev libpcre3-dev
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: ${{ matrix.nim }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: nimble install -y arraymancer nimpy
      - name: Compile nimplex
        run: nim c -d:release nimplex.nim
      - name: Run grid tests
        run: nim c -r -d:release tests/grid.nim 
      - name: Run graph tests
        run: nim c -r -d:release tests/graph.nim
      - name: Run CLI tests
        run: nim c -r -d:release tests/cli.nim
      - name: Run stitching tests
        run: nim c -r -d:release tests/stitching.nim