name: Windows Tests 

on:
  push:
    paths:
      - 'tests/**'
      - 'nimplex.nim'
      - '.github/workflows/testingOnPush_Windows.yaml'
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: '3.10'
      - name: Install Nim
        run: conda install -c conda-forge libopenblas mkl
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '2.0.2'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: nimble install -y arraymancer nimpy
      - name: Compile nimplex
        run: nim c -d:release nimplex.nim
      - name: Run grid tests
        run: nim c -r -d:release tests/grid.nim 
      - name: Run graph tests
        run: nim c -r -d:release tests/graph.nim
      - name: Run CLI tests
        run: nim c -r -d:release tests/cli.nim